networks:
  backend:
    driver: bridge

services:
  postgres:
    image: docker.io/postgres:16-alpine
    container_name: mybackendtemplate-db
    restart: unless-stopped
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432" # exposing postgres port to host for local development, must be omitted in production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/redis:7-alpine
    container_name: mybackendtemplate-redis
    restart: unless-stopped
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Src/API/Dockerfile
    container_name: mybackendtemplate-api
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: mybackendtemplate-nginx
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./Nginx/ssl:/etc/nginx/ssl:ro,Z
      - nginx_cache:/var/cache/nginx:Z
      - ./Tests/test_oauth:/usr/share/nginx/html/test_oauth:ro,Z
    depends_on:
      - api

  seq:
    image: datalust/seq:latest
    container_name: mybackendtemplate-seq
    restart: unless-stopped
    networks:
      - backend
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: mybackendtemplate-rabbitmq
    restart: unless-stopped
    networks:
      - backend
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
  nginx_cache:
    driver: local
